PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS EmailHashes (
	id INTEGER PRIMARY KEY ASC,
	hash VARCHAR(32) UNIQUE,
	disabled INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS AvatarHashes (
	id INTEGER PRIMARY KEY ASC,
	emailID INTEGER,
	hash VARCHAR(40) UNIQUE,
	disabled INTEGER DEFAULT 0,

	FOREIGN KEY (emailID) REFERENCES EmailHashes(id)
);
